import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")
const snapshotExists = await Bun.file(snapshotPath).exists()

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
let modelsData = ""
if (process.env.MODELS_DEV_API_JSON) {
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else if (snapshotExists) {
  console.log("Using existing models-snapshot.js (offline mode)")
} else {
  modelsData = await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
}

if (modelsData) {
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.js"),
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.d.ts"),
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log("Generated models-snapshot.js")
}
